
### 1. Data Description

The data used in this project comes from the **ECO (Electricity Consumption and Occupancy) dataset**. This analysis focuses on plug data for all appliances in the dataset and smart meter data from Households 4, 5, and 6.The plug data records individual appliance consumption, while the smart meter data records total household consumption.

The original data was sampled at a frequency of 1 Hz, meaning power consumption was recorded once per second in **watts (W)**. This results in **86,400 measurements per day**. The dataset covers the period from **June 27 to January 31**, although some days and individual values are missing. Missing values are stored as −1 in the original dataset.<br>


### 2. Research Questions

For the given households and their energy usage, we are curious about these questions:

1. Which household has the highest total electricity consumption, and how does their daily consumption change over time?

2. How does appliance energy consumption vary throughout the day for each household?

3. How does entertainment appliance usage differ between households over time?<br>


### 3. Data Preparation

Missing values were replaced using **linear interpolation**, since electricity consumption typically changes gradually over time.

The data was then **resampled from 1-second intervals to hourly intervals**. During this process, power measurements in watts were converted to energy consumption in **kilowatt-hours (kWh)**, which is more suitable for comparing energy usage.

All plug data was combined into a long-format table containing `household`, `appliance`, `datetime`, and `energy consumption`. Smart meter data was processed similarly to create a table containing `household`, `datetime`, and `total energy consumption`.


```{python}
import numpy as np
import pandas as pd
from pathlib import Path
```

```{python}
#| eval: false
def process_plug_file(filepath, house, appliance):
    df = pd.read_csv(filepath)
    df = df.replace(-1, np.nan) # dealing with missing val
    df = df.interpolate(method='linear')
    #print(df.dtypes)
    # df = pd.to_numeric(df errors='coerce')
    date = pd.to_datetime(filepath.stem[:10]) # get date from filename
    df['datetime'] = pd.date_range( # create datetime index
        start=date,
        periods=len(df),
        freq="s"
    ) 
    df = df.set_index("datetime")
    csp = df.columns[-1]
    df[csp] = pd.to_numeric(df[csp], errors="coerce")
    hourly = df[csp].resample("1h").sum() # unit conversions resampling
    hourly = hourly / 3600000 # convert to kWh
    result = pd.DataFrame({
        "house": house,
        "appliance": appliance,
        "datetime": hourly.index,
        "consumption_kWh": hourly.values
    })
    return result

## process smart meter data
def process_sm_file(filepath, house):
    df = pd.read_csv(filepath)
    df = df.replace(-1, np.nan) 
    date = pd.to_datetime(filepath.stem[:10])
    df['datetime'] = pd.date_range(
        start=date,
        periods=len(df),
        freq="s"
    )
    df = df.set_index("datetime")
    total_csp = df.columns[0]
    df[total_csp] = pd.to_numeric(df[total_csp], errors="coerce")
    hourly = df[total_csp].resample("1h").sum() / 3600000
    result = pd.DataFrame({
            "house": house,
            "datetime": hourly.index,
            "power_all_phases_kWh": hourly.values
        })
    return result

```


``` {python}
#| eval: false
data_path = Path('data')
output_path = Path('processed_data')
plug_df = []
sm_df = []

id_to_app_map_04 = {'01': 'Fridge', '02': 'Kitchen appliances','03': 'Lamp','04': 'Stereo and laptop',
'05': 'Freezer','06': 'Tablet','07': 'Entertainment','08': 'Microwave' }

id_to_app_map_05 = {'01': 'Tablet', '02': 'Coffee machine','03': 'Fountain','04': 'Microwave',
'05': 'Fridge','06': 'Entertainment','07': 'PC','08': 'Kettle' }

id_to_app_map_06 = {'01': 'Lamp', '02': 'Laptop','03': 'Router','04': 'Coffee machine',
'05': 'Entertainment','06': 'Fridge','07': 'Kettle' }

id_to_house_map = {
    '04':id_to_app_map_04,
    '05':id_to_app_map_05,
    '06':id_to_app_map_06
}

for folder in data_path.iterdir():
    if not folder.is_dir():
        continue
    house_name = folder.name.split('_')[0]
    map_id = id_to_house_map.get(house_name)
    # plug folders
    if not folder.name.endswith("sm"):
        for f in folder.iterdir():
            if not f.is_dir():
                continue
            appliance_name = map_id.get(f.name)
            for csvfile in sorted(f.glob("*.csv")):
                result = process_plug_file(
                    csvfile,
                    house_name,
                    appliance_name
                )
                plug_df.append(result)
            
    # smart meter folders
    elif folder.name.endswith("sm"):
        for csvfile in sorted(folder.glob("*.csv")):
            result = process_sm_file(
                csvfile,
                house_name
            )
            sm_df.append(result)

plug_df = pd.concat(plug_df)
sm_df = pd.concat(sm_df)

plug_df.to_csv(output_path/'plug_data.csv',index=False)
sm_df.to_csv(output_path/'sm_data.csv',index=False)
```

### 4. EDA for Energy Consumption

```{python}
plug_data = pd.read_csv('processed_data/plug_data.csv')
sm_data = pd.read_csv('processed_data/sm_data.csv')

print(plug_data.groupby(['house','appliance']).describe())
print(sm_data.groupby(['house']).describe())
```

